apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flatris-ingress
  namespace: flatris
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - flatris.saikbiradar.in
    secretName: flatris-tls
  rules:
  - host: flatris.saikbiradar.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flatris-service
            port:
              number: 80
